const xlsx = require("xlsx");
const path = "c:/Users/Administrator/Documents/tnja-frontend/public/templates/coaches_import_template.xlsx";
const wb = xlsx.readFile(path);

const coaches = [
  { "Full Name": "Rajesh Kumar", "Father Name": "Muthusamy", "Email": "rajesh.kumar.coach1@example.com", "Mobile Number": "9840010001", "Aadhaar Number": "930000000001", "Date of Birth": "1985-03-14", "Gender": "MALE", "District Name": "Salem", "Taluk Name": "Salem", "Blood Group": "O+", "Pincode": "636001", "History in Judo": "8 years coaching at district level", "History in Other Martial": "Karate - Brown Belt", "Present Grade in Judo": "Black Belt 2nd Dan", "Status": "APPROVED", "Temporary ID": "", "Permanent ID": "" },
  { "Full Name": "Priya Lakshmanan", "Father Name": "Lakshmanan", "Email": "priya.lakshmanan.coach2@example.com", "Mobile Number": "9840010002", "Aadhaar Number": "930000000002", "Date of Birth": "1990-07-22", "Gender": "FEMALE", "District Name": "Coimbatore", "Taluk Name": "Coimbatore North", "Blood Group": "A+", "Pincode": "641001", "History in Judo": "5 years coaching school-level students", "History in Other Martial": "None", "Present Grade in Judo": "Black Belt 1st Dan", "Status": "APPROVED", "Temporary ID": "", "Permanent ID": "" },
  { "Full Name": "Selvam Andi", "Father Name": "Andi Thevar", "Email": "selvam.andi.coach3@example.com", "Mobile Number": "9840010003", "Aadhaar Number": "930000000003", "Date of Birth": "1982-11-05", "Gender": "MALE", "District Name": "Madurai", "Taluk Name": "Madurai South", "Blood Group": "B+", "Pincode": "625001", "History in Judo": "12 years, former state-level player", "History in Other Martial": "Silambam", "Present Grade in Judo": "Black Belt 3rd Dan", "Status": "APPROVED", "Temporary ID": "", "Permanent ID": "" },
  { "Full Name": "Kavitha Ramesh", "Father Name": "Ramesh Babu", "Email": "kavitha.ramesh.coach4@example.com", "Mobile Number": "9840010004", "Aadhaar Number": "930000000004", "Date of Birth": "1993-01-30", "Gender": "FEMALE", "District Name": "Tiruchirappalli", "Taluk Name": "Srirangam", "Blood Group": "AB+", "Pincode": "620006", "History in Judo": "4 years coaching at club level", "History in Other Martial": "None", "Present Grade in Judo": "Brown Belt", "Status": "APPROVED", "Temporary ID": "", "Permanent ID": "" },
  { "Full Name": "Suresh Babu", "Father Name": "Krishnan", "Email": "suresh.babu.coach5@example.com", "Mobile Number": "9840010005", "Aadhaar Number": "930000000005", "Date of Birth": "1978-09-18", "Gender": "MALE", "District Name": "Vellore", "Taluk Name": "Katpadi", "Blood Group": "O-", "Pincode": "632001", "History in Judo": "15 years, national referee panel", "History in Other Martial": "Taekwondo - Black Belt", "Present Grade in Judo": "Black Belt 4th Dan", "Status": "APPROVED", "Temporary ID": "", "Permanent ID": "" },
  { "Full Name": "Deepa Saravanan", "Father Name": "Saravanan", "Email": "deepa.saravanan.coach6@example.com", "Mobile Number": "9840010006", "Aadhaar Number": "930000000006", "Date of Birth": "1991-05-09", "Gender": "FEMALE", "District Name": "Erode", "Taluk Name": "Erode", "Blood Group": "A-", "Pincode": "638001", "History in Judo": "6 years coaching, district panel referee", "History in Other Martial": "None", "Present Grade in Judo": "Black Belt 1st Dan", "Status": "APPROVED", "Temporary ID": "", "Permanent ID": "" },
  { "Full Name": "Manikandan Velu", "Father Name": "Velusamy", "Email": "manikandan.velu.coach7@example.com", "Mobile Number": "9840010007", "Aadhaar Number": "930000000007", "Date of Birth": "1987-12-25", "Gender": "MALE", "District Name": "Thanjavur", "Taluk Name": "Thanjavur", "Blood Group": "B-", "Pincode": "613001", "History in Judo": "9 years coaching, zonal level", "History in Other Martial": "Kalaripayattu", "Present Grade in Judo": "Black Belt 2nd Dan", "Status": "APPROVED", "Temporary ID": "", "Permanent ID": "" },
  { "Full Name": "Anitha Subramani", "Father Name": "Subramani", "Email": "anitha.subramani.coach8@example.com", "Mobile Number": "9840010008", "Aadhaar Number": "930000000008", "Date of Birth": "1995-02-17", "Gender": "FEMALE", "District Name": "Kanniyakumari", "Taluk Name": "Agastheeswaram", "Blood Group": "O+", "Pincode": "629001", "History in Judo": "3 years coaching, school level", "History in Other Martial": "None", "Present Grade in Judo": "Blue Belt", "Status": "PENDING", "Temporary ID": "", "Permanent ID": "" },
  { "Full Name": "Dinesh Kannan", "Father Name": "Kannan Pillai", "Email": "dinesh.kannan.coach9@example.com", "Mobile Number": "9840010009", "Aadhaar Number": "930000000009", "Date of Birth": "1980-06-11", "Gender": "MALE", "District Name": "Dindigul", "Taluk Name": "Dindigul East", "Blood Group": "AB-", "Pincode": "624001", "History in Judo": "11 years, former national player", "History in Other Martial": "Judo referee - International panel", "Present Grade in Judo": "Black Belt 3rd Dan", "Status": "APPROVED", "Temporary ID": "", "Permanent ID": "" },
  { "Full Name": "Meena Gopal", "Father Name": "Gopalakrishnan", "Email": "meena.gopal.coach10@example.com", "Mobile Number": "9840010010", "Aadhaar Number": "930000000010", "Date of Birth": "1989-10-03", "Gender": "FEMALE", "District Name": "Tirunelveli", "Taluk Name": "Palayamkottai", "Blood Group": "A+", "Pincode": "627002", "History in Judo": "7 years coaching, district level", "History in Other Martial": "None", "Present Grade in Judo": "Black Belt 1st Dan", "Status": "APPROVED", "Temporary ID": "", "Permanent ID": "" }
];

const headers = ["Full Name","Father Name","Email","Mobile Number","Aadhaar Number","Date of Birth","Gender","District Name","Taluk Name","Blood Group","Pincode","History in Judo","History in Other Martial","Present Grade in Judo","Status","Temporary ID","Permanent ID"];
const newCoachSheet = xlsx.utils.json_to_sheet(coaches, { header: headers });

const newWb = xlsx.utils.book_new();
xlsx.utils.book_append_sheet(newWb, wb.Sheets["Instructions"], "Instructions");
xlsx.utils.book_append_sheet(newWb, newCoachSheet, "Coaches");
xlsx.utils.book_append_sheet(newWb, wb.Sheets["Districts & Taluks"], "Districts & Taluks");

const outPath = "C:/Users/ADMINI~1/AppData/Local/Temp/claude/c--Users-Administrator-Documents-tnja-frontend/5036e709-07b9-43c1-94b2-6debb73e22ee/scratchpad/coaches_import_10_ready.xlsx";
xlsx.writeFile(newWb, outPath);
console.log("Written to", outPath);
