const fs = require('fs');
const file = 'src/controllers/tournamentController.ts';
let code = fs.readFileSync(file, 'utf8');
code = code.replace(/const \{ id \} = req\.params;/g, 'const id = req.params.id as string;');
code = code.replace(/const \{ id: tournamentId, regId \} = req\.params;/g, 'const tournamentId = req.params.id as string;\n  const regId = req.params.regId as string;');
code = code.replace(/districtApproval,/g, 'districtApproval: districtApproval as any,');
code = code.replace(/stateApproval,/g, 'stateApproval: stateApproval as any,');
code = code.replace(/registration\.player\.id/g, 'registration.playerId');
code = code.replace(/sendNotificationToUser\(tournament\.clubId, \{/g, 'if (tournament.clubId) {\n      sendNotificationToUser(tournament.clubId, {');
code = code.replace(/type: \"TOURNAMENT_UPDATED\",\n\s+message: \`Tournament \"\$\{tournament\.title\}\" has been updated\.\`,\n\s+tournamentId: id,\n\s+createdAt: new Date\(\)\.toISOString\(\),\n\s+\}\);/g, 'type: \"TOURNAMENT_UPDATED\",\n        message: \`Tournament \"\$\{tournament.title\}\" has been updated.\`,\n        tournamentId: id,\n        createdAt: new Date().toISOString(),\n      });\n    }');
code = code.replace(/type: \"TOURNAMENT_DELETED\",\n\s+message: \`Tournament \"\$\{tournament\.title\}\" has been deleted\.\`,\n\s+tournamentId: id,\n\s+createdAt: new Date\(\)\.toISOString\(\),\n\s+\}\);/g, 'type: \"TOURNAMENT_DELETED\",\n        message: \`Tournament \"\$\{tournament.title\}\" has been deleted.\`,\n        tournamentId: id,\n        createdAt: new Date().toISOString(),\n      });\n    }');
fs.writeFileSync(file, code);
